[metadata]
# License check configuration for ml-audit-platform
# Defines allowed and forbidden licenses for compliance

[allowed]
# These licenses are ALLOWED in the project
Apache Software License
Apache License 2.0
Apache License, Version 2.0
Apache 2.0
BSD
BSD License
BSD-3-Clause
BSD-2-Clause
Simplified BSD
MIT
MIT License
Python Software Foundation License
ISC License (ISCL)
Mozilla Public License 2.0 (MPL 2.0)
Public Domain
The Unlicense
Zope Public License

[forbidden]
# These licenses are FORBIDDEN in the project
GNU General Public License v3 (GPLv3)
GNU General Public License v3 or later (GPLv3+)
GNU General Public License v2 (GPLv2)
GNU General Public License v2 or later (GPLv2+)
GNU Affero General Public License v3
GNU Affero General Public License v3 or later
GNU Lesser General Public License v2 (LGPLv2)
GNU Lesser General Public License v2 or later (LGPLv2+)
GNU Lesser General Public License v3 (LGPLv3)
GNU Lesser General Public License v3 or later (LGPLv3+)
Affero General Public License
SSPL (Server Side Public License)
Commons Clause
Business Source License

